#![doc = include_str!("../README.md")]
#![no_std]

/// Defines a structure with precise bit-level and byte-level fields.
///
/// For structs, this macro generates a `#[repr(C, packed)]` struct
/// backed by a tightly packed `[u8; N]` array,
/// along with constant-time getter methods for extracting
/// sub-byte, unaligned, or standard fields.
///
/// For enums, it generates a `#[repr(uN)]` enum (up to 128 bits)
/// with strongly typed variants, safely parsing underlying bit patterns
/// and ensuring exhaustive coverage of all possible states.
///
/// # Syntax
///
/// The macro uses a custom syntax to define
/// the total size and the exact placement of each field
/// or enum variants:
///
/// ### Structs
///
/// ```rust
/// use bitx::bits;
///
/// bits! {
///     /// Outer attributes are supported
///     pub struct Header: u36 { // 36 bits struct
///         // 1-bit fields automatically return `bool`
///         0.0;01 pub is_active,
///
///         // Custom nested types are supported
///         0.1;03 pub state: State,
///
///         // 20-bit integer; custom bit-widths are supported
///         1.0;20 pub(crate) payload,
///
///         // Unaligned cross-byte field
///         #[allow(dead_code)]
///         3.4;08 checksum,
///     }
/// }
/// ```
///
/// ### Enums
///
/// Enums map specific bit patterns to variants.
/// You must define the bit size,
/// and the macro ensures the enum is not less-covered/overstuffed.
///
/// ```rust
/// use bitx::bits;
///
/// bits! {
///     pub enum State: u3 {
///         0         => Inactive,
///         1         => Active,
///         2 | 6..=7 => Error,   // Arbitrary bit patterns
///         _         => Unknown, // Default fallback for unmapped bit patterns
///     }
/// }
/// ```
///
/// # Layouts
///
/// Layouts for individual fields use a `<byte>.<bit>;<size>` format:
///
/// - `byte`: The byte offset.
/// - `bit`: The bit offset within the byte. Must be between 0 and 7.
/// - `size`: The size of the field, in bits.
///
/// # Generated API
///
/// For both structs and enums, the macro generates:
///
/// - `pub const fn from_array(value: [u8; SIZE]) -> Self`
///
/// When reading from a slice, the return type differs
/// to prevent unaligned read of multibyte integer:
///
/// - Struct: `pub const fn from_slice(value: &[u8]) -> Option<&Self>`
/// - Enum: `pub const fn from_slice(value: &[u8]) -> Option<Self>`
///
/// Structs also receive generated constant-time field getters.
///
pub use bitx_macros::bits;

/// A trait representing bit-manipulatability of struct.
///
/// Since macro automatically implements and manages this trait,
/// It's highly discouraged that manually implementing this trait.
pub trait Bits {
    /// A mask type to extract data from byte stream.
    ///
    /// Unit type will be used for structs larger than 128-bit.
    type Mask;

    /// A declared size of struct, in bits.
    const BITS: u32;
}

#[doc(hidden)]
#[inline(always)]
#[expect(
    clippy::inline_always,
    reason = "ideally, only single inst. will be generated by LLVM; \
              inlining is required to dedup. checks in context."
)]
pub const fn copy(dst: &mut [u8], src: &[u8]) {
    let len = dst.len();
    assert!(src.len() >= len);

    // NOTE: `.copy_from_slice` is not stable before MSRV 1.87
    let mut i = 0;
    while i < len {
        dst[i] = src[i];
        i += 1;
    }
}
