[package]
name = "bitx-macros"
description = "proc-macro stubs for `bitx` crate"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
quote.workspace = true
proc-macro2.workspace = true

[dev-dependencies]
paste.workspace = true

[lints]
workspace = true
